/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progdesktop2025.view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author jogos
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainClientesButton = new javax.swing.JButton();
        mainFuncionariosButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainProdutosButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainClientesButton.setText("Clientes");
        mainClientesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainClientesButtonMouseClicked(evt);
            }
        });

        mainFuncionariosButton.setText("Functionarios");
        mainFuncionariosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainFuncionariosButtonMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema Mercado");

        mainProdutosButton.setText("Produtos");
        mainProdutosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainProdutosButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(mainClientesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(mainFuncionariosButton)
                .addGap(36, 36, 36)
                .addComponent(mainProdutosButton)
                .addGap(31, 31, 31))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainClientesButton)
                    .addComponent(mainFuncionariosButton)
                    .addComponent(mainProdutosButton))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainChangeScreen() {
        this.setVisible(false);
    }
    
    private void mainChangeScreenAgain() {
        this.setVisible(true);
    }

    private void mainClientesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainClientesButtonMouseClicked
        ClienteView clienteView = new ClienteView();
        clienteView.setVisible(true);
        
        clienteView.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        clienteView.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                mainChangeScreenAgain();
            }
        });

        this.mainChangeScreen();
    }//GEN-LAST:event_mainClientesButtonMouseClicked

    private void mainFuncionariosButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainFuncionariosButtonMouseClicked
        FuncionarioView funcionarioView = new FuncionarioView();
        funcionarioView.setVisible(true);
        
        funcionarioView.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        funcionarioView.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                mainChangeScreenAgain();
            }
        });

        this.mainChangeScreen();
    }//GEN-LAST:event_mainFuncionariosButtonMouseClicked

    private void mainProdutosButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainProdutosButtonMouseClicked
        ProdutoView produtoView = new ProdutoView();
        produtoView.setVisible(true);
        
        
        produtoView.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        produtoView.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                mainChangeScreenAgain();
            }
        });

        this.mainChangeScreen();
    }//GEN-LAST:event_mainProdutosButtonMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mainClientesButton;
    private javax.swing.JButton mainFuncionariosButton;
    private javax.swing.JButton mainProdutosButton;
    // End of variables declaration//GEN-END:variables
}
